### ISSUE TITLE
Unable to use Ambiguous types (union, json object)

### ISSUE THREAD

**Issue by DanielHall977** [autoinvent/magql#60]
When using an ambiguous type, undefined object, union, json object.
Goal is to be able to pass any json we want.
```
somt-api_1  | 172.18.0.6 - - [27/Apr/2021 23:09:28] "POST /graphql HTTP/1.1" 500 -
somt-api_1  | Traceback (most recent call last):
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/flask/cli.py", line 83, in find_best_app
somt-api_1  |     app = call_factory(script_info, app_factory)
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/flask/cli.py", line 119, in call_factory
somt-api_1  |     return app_factory()
somt-api_1  |   File "/opt/project/src/som/__init__.py", line 54, in create_app
somt-api_1  |     from som.schema import schema
somt-api_1  |   File "/opt/project/src/som/schema.py", line 18, in <module>
somt-api_1  |     from som.model.coa_unit import coa_unit_manager
somt-api_1  |   File "/opt/project/src/som/model/coa_unit.py", line 27, in <module>
somt-api_1  |     class COAUnit(db.Model):
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/flask_sqlalchemy/model.py", line 67, in __init__
somt-api_1  |     super(NameMetaMixin, cls).__init__(name, bases, d)
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/flask_sqlalchemy/model.py", line 121, in __init__
somt-api_1  |     super(BindMetaMixin, cls).__init__(name, bases, d)
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/ext/declarative/api.py", line 76, in __init__
somt-api_1  |     _as_declarative(cls, classname, cls.__dict__)
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/ext/declarative/base.py", line 131, in _as_declarative
somt-api_1  |     _MapperConfig.setup_mapping(cls, classname, dict_)
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/ext/declarative/base.py", line 160, in setup_mapping
somt-api_1  |     cfg_cls(cls_, classname, dict_)
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/ext/declarative/base.py", line 190, in __init__
somt-api_1  |     self._setup_table()
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/ext/declarative/base.py", line 534, in _setup_table
somt-api_1  |     cls.__table__ = table = table_cls(
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/flask_sqlalchemy/model.py", line 90, in __table_cls__
somt-api_1  |     return sa.Table(*args, **kwargs)
somt-api_1  |   File "<string>", line 2, in __new__
somt-api_1  |     
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
somt-api_1  |     return fn(*args, **kwargs)
somt-api_1  |   File "/opt/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 540, in __new__
somt-api_1  |     raise exc.InvalidRequestError(
somt-api_1  | sqlalchemy.exc.InvalidRequestError: Table 'my_table' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object
```

**Comment by davidism** [comment]
Just merged in the rewrite, if I understand this issue correctly it shouldn't be a problem anymore.
